basePath: /api/v2
definitions:
  dto.CreateExampleRequest:
    properties:
      count:
        minimum: 0
        type: integer
      name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - count
    - name
    type: object
  dto.CreateExampleResponse:
    properties:
      example:
        $ref: '#/definitions/entities.ExampleEntity'
    type: object
  dto.DeleteExampleResponse:
    properties:
      id:
        type: integer
    type: object
  dto.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  dto.GetAllExamplesResponse:
    properties:
      examples:
        items:
          $ref: '#/definitions/entities.ExampleEntity'
        type: array
    type: object
  dto.GetByIdExampleResponse:
    properties:
      example:
        $ref: '#/definitions/entities.ExampleEntity'
    type: object
  dto.UpdateExampleRequest:
    properties:
      count:
        minimum: 0
        type: integer
      name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - count
    - name
    type: object
  dto.UpdateExampleResponse:
    properties:
      id:
        type: integer
    type: object
  entities.ExampleEntity:
    properties:
      count:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: This is the CRUD service for our hackathon template.
  title: CRUD Service API
  version: "1.0"
paths:
  /examples:
    get:
      consumes:
      - application/json
      description: Retrieves a list of example entities. Accepts an optional JSON
        payload to filter, sort or paginate the results.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllExamplesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get all examples
      tags:
      - Examples
    post:
      consumes:
      - application/json
      description: Creates a new example entity.
      parameters:
      - description: Create example request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateExampleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new example
      tags:
      - Examples
  /examples/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an example entity by ID.
      parameters:
      - description: Example ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeleteExampleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete an example
      tags:
      - Examples
    get:
      consumes:
      - application/json
      description: Retrieves a single example entity by its ID.
      parameters:
      - description: Example ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetByIdExampleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get example by ID
      tags:
      - Examples
    put:
      consumes:
      - application/json
      description: Updates an example entity by ID.
      parameters:
      - description: Example ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update example request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateExampleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateExampleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Update an existing example
      tags:
      - Examples
swagger: "2.0"
